# Generated by Django 4.1.1 on 2022-09-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimage',
            name='user',
            field=models.CharField(default='myname', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='uploadimage',
            name='caption',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='uploadimage',
            name='image',
            field=models.ImageField(upload_to='img/%y'),
        ),
    ]
